# Generated by Django 4.2.10 on 2024-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('essential_oil', 'Essential Oil'), ('diffuser', 'Diffuser'), ('ready_to_use_kit', 'Ready to Use Kit')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('features', models.TextField(blank=True, help_text='Key features of the product')),
                ('contents', models.TextField(blank=True, help_text='Contents of the product, if applicable')),
            ],
        ),
        migrations.DeleteModel(
            name='Diffuser',
        ),
        migrations.DeleteModel(
            name='EssentialOil',
        ),
        migrations.DeleteModel(
            name='ReadyToUseKit',
        ),
    ]
