# Generated by Django 4.2.10 on 2024-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('essential_oil', 'Essential Oil'), ('diffuser', 'Diffuser'), ('roll_on', 'Roll On')], max_length=50),
        ),
    ]
